# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: "Flutter Analyze & Test"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run tests on (defaults to the workflow trigger ref)'
        required: false
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flutter-version: [ '3.32.7', '3.10.5' ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch != '' && github.event.inputs.branch || github.ref }}

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: ${{ matrix.flutter-version }}

      - name: Cache pub packages and tool state
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            .dart_tool
          key: ${{ runner.os }}-pub-${{ matrix.flutter-version }}-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-${{ matrix.flutter-version }}-

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project source
        run: flutter analyze

  test:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        flutter-version: [ '3.32.7', '3.10.5' ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch != '' && github.event.inputs.branch || github.ref }}

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: ${{ matrix.flutter-version }}

      - name: Cache pub packages and tool state
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            .dart_tool
          key: ${{ runner.os }}-pub-${{ matrix.flutter-version }}-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-${{ matrix.flutter-version }}-

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test
